export const StaffData = [
<<<<<<< HEAD
  {
    id: "EMP001",
    staffName: "김민수",
    dept: "운영팀",
    position: "매니저",
    phone: "010-1234-5678",
    email: "minsu.kim@cinema.com",
    theater: "강남점",
    hireDate: "2023-01-15",
    shiftType: "풀타임",
    role: "지점 관리",
    status: "근무중",
  },
  {
    id: "EMP002",
    staffName: "이서연",
    dept: "고객서비스팀",
    position: "대리",
    phone: "010-2345-6789",
    email: "seoyeon.lee@cinema.com",
    theater: "강남점",
    hireDate: "2023-06-01",
    shiftType: "풀타임",
    role: "매표",
    status: "근무중",
  },
  {
    id: "EMP003",
    staffName: "박지훈",
    dept: "운영팀",
    position: "사원",
    phone: "010-3456-7890",
    email: "jihoon.park@cinema.com",
    theater: "여의도점",
    hireDate: "2024-03-10",
    shiftType: "파트타임",
    role: "안내",
    status: "휴가",
  },
  {
    id: "EMP004",
    staffName: "최유진",
    dept: "매점팀",
    position: "사원",
    phone: "010-4567-8901",
    email: "yujin.choi@cinema.com",
    theater: "강남점",
    hireDate: "2024-07-20",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "근무중",
  },
  {
    id: "EMP005",
    staffName: "강현우",
    dept: "상영관팀",
    position: "대리",
    phone: "010-5678-9012",
    email: "hyunwoo.kang@cinema.com",
    theater: "여의도점",
    hireDate: "2022-11-05",
    shiftType: "풀타임",
    role: "상영관 관리",
    status: "퇴근",
  },
  {
    id: "EMP006",
    staffName: "정소연",
    dept: "고객서비스팀",
    position: "사원",
    phone: "010-6789-0123",
    email: "soyeon.jung@cinema.com",
    theater: "신촌점",
    hireDate: "2023-09-12",
    shiftType: "파트타임",
    role: "고객 응대",
    status: "근무중",
  },
  {
    id: "EMP007",
    staffName: "오태현",
    dept: "운영팀",
    position: "매니저",
    phone: "010-7890-1234",
    email: "taehyun.oh@cinema.com",
    theater: "신촌점",
    hireDate: "2021-04-01",
    shiftType: "풀타임",
    role: "지점 관리",
    status: "퇴사",
  },
  {
    id: "EMP008",
    staffName: "한지민",
    dept: "매점팀",
    position: "사원",
    phone: "010-8901-2345",
    email: "jimin.han@cinema.com",
    theater: "강남점",
    hireDate: "2024-02-14",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "근무중",
  },
  {
    id: "EMP009",
    staffName: "윤도현",
    dept: "상영관팀",
    position: "사원",
    phone: "010-9012-3456",
    email: "dohyun.yoon@cinema.com",
    theater: "여의도점",
    hireDate: "2023-12-01",
    shiftType: "풀타임",
    role: "상영관 관리",
    status: "휴가",
  },
  {
    id: "EMP010",
    staffName: "서민재",
    dept: "고객서비스팀",
    position: "대리",
    phone: "010-0123-4567",
    email: "minjae.seo@cinema.com",
    theater: "신촌점",
    hireDate: "2022-08-20",
    shiftType: "풀타임",
    role: "매표",
    status: "근무중",
  },
  {
    id: "EMP011",
    staffName: "김하늘",
    dept: "매점팀",
    position: "사원",
    phone: "010-1122-3344",
    email: "haneul.kim@cinema.com",
    theater: "홍대점",
    hireDate: "2024-05-10",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "퇴근",
  },
  {
    id: "EMP012",
    staffName: "이준호",
    dept: "상영관팀",
    position: "사원",
    phone: "010-2233-4455",
    email: "junho.lee@cinema.com",
    theater: "명동점",
    hireDate: "2023-03-22",
    shiftType: "풀타임",
    role: "상영관 관리",
    status: "근무중",
  },
  {
    id: "EMP013",
    staffName: "박소영",
    dept: "고객서비스팀",
    position: "사원",
    phone: "010-3344-5566",
    email: "soyoung.park@cinema.com",
    theater: "홍대점",
    hireDate: "2024-01-15",
    shiftType: "파트타임",
    role: "고객 응대",
    status: "휴가",
  },
  {
    id: "EMP014",
    staffName: "최민혁",
    dept: "운영팀",
    position: "대리",
    phone: "010-4455-6677",
    email: "minhyuk.choi@cinema.com",
    theater: "강남점",
    hireDate: "2022-07-01",
    shiftType: "풀타임",
    role: "운영 지원",
    status: "근무중",
  },
  {
    id: "EMP015",
    staffName: "강지윤",
    dept: "매점팀",
    position: "사원",
    phone: "010-5566-7788",
    email: "jiyoon.kang@cinema.com",
    theater: "여의도점",
    hireDate: "2024-06-05",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "근무중",
  },
  {
    id: "EMP016",
    staffName: "정우진",
    dept: "상영관팀",
    position: "사원",
    phone: "010-6677-8899",
    email: "woojin.jung@cinema.com",
    theater: "신촌점",
    hireDate: "2023-11-20",
    shiftType: "풀타임",
    role: "상영관 관리",
    status: "근무중",
  },
  {
    id: "EMP017",
    staffName: "오세진",
    dept: "고객서비스팀",
    position: "대리",
    phone: "010-7788-9900",
    email: "sejin.oh@cinema.com",
    theater: "명동점",
    hireDate: "2022-09-10",
    shiftType: "풀타임",
    role: "매표",
    status: "근무중",
  },
  {
    id: "EMP018",
    staffName: "한수민",
    dept: "매점팀",
    position: "사원",
    phone: "010-8899-0011",
    email: "sumin.han@cinema.com",
    theater: "강남점",
    hireDate: "2024-04-01",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "휴가",
  },
  {
    id: "EMP019",
    staffName: "윤지성",
    dept: "운영팀",
    position: "매니저",
    phone: "010-9900-1122",
    email: "jisung.yoon@cinema.com",
    theater: "홍대점",
    hireDate: "2021-06-15",
    shiftType: "풀타임",
    role: "지점 관리",
    status: "퇴사",
  },
  {
    id: "EMP020",
    staffName: "서예린",
    dept: "고객서비스팀",
    position: "사원",
    phone: "010-0011-2233",
    email: "yerin.seo@cinema.com",
    theater: "여의도점",
    hireDate: "2023-10-05",
    shiftType: "파트타임",
    role: "고객 응대",
    status: "퇴근",
  },
  {
    id: "EMP021",
    staffName: "김지우",
    dept: "상영관팀",
    position: "사원",
    phone: "010-1122-4455",
    email: "jiwoo.kim@cinema.com",
    theater: "신촌점",
    hireDate: "2024-02-20",
    shiftType: "파트타임",
    role: "상영관 관리",
    status: "근무중",
  },
  {
    id: "EMP022",
    staffName: "이도윤",
    dept: "매점팀",
    position: "사원",
    phone: "010-2233-5566",
    email: "doyoon.lee@cinema.com",
    theater: "명동점",
    hireDate: "2024-08-01",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "근무중",
  },
  {
    id: "EMP023",
    staffName: "박하린",
    dept: "고객서비스팀",
    position: "대리",
    phone: "010-3344-6677",
    email: "harin.park@cinema.com",
    theater: "강남점",
    hireDate: "2022-12-10",
    shiftType: "풀타임",
    role: "매표",
    status: "근무중",
  },
  {
    id: "EMP024",
    staffName: "최태민",
    dept: "운영팀",
    position: "사원",
    phone: "010-4455-7788",
    email: "taemin.choi@cinema.com",
    theater: "홍대점",
    hireDate: "2023-05-15",
    shiftType: "풀타임",
    role: "운영 지원",
    status: "퇴근",
  },
  {
    id: "EMP025",
    staffName: "강서준",
    dept: "상영관팀",
    position: "사원",
    phone: "010-5566-8899",
    email: "seojun.kang@cinema.com",
    theater: "여의도점",
    hireDate: "2024-03-01",
    shiftType: "파트타임",
    role: "상영관 관리",
    status: "휴가",
  },
  {
    id: "EMP026",
    staffName: "정민아",
    dept: "매점팀",
    position: "사원",
    phone: "010-6677-9900",
    email: "mina.jung@cinema.com",
    theater: "신촌점",
    hireDate: "2024-07-10",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "근무중",
  },
  {
    id: "EMP027",
    staffName: "오현서",
    dept: "고객서비스팀",
    position: "사원",
    phone: "010-7788-0011",
    email: "hyunseo.oh@cinema.com",
    theater: "명동점",
    hireDate: "2023-08-20",
    shiftType: "풀타임",
    role: "고객 응대",
    status: "근무중",
  },
  {
    id: "EMP028",
    staffName: "한지호",
    dept: "운영팀",
    position: "대리",
    phone: "010-8899-1122",
    email: "jiho.han@cinema.com",
    theater: "강남점",
    hireDate: "2022-05-01",
    shiftType: "풀타임",
    role: "운영 지원",
    status: "근무중",
  },
  {
    id: "EMP029",
    staffName: "윤서하",
    dept: "매점팀",
    position: "사원",
    phone: "010-9900-2233",
    email: "seoha.yoon@cinema.com",
    theater: "홍대점",
    hireDate: "2024-04-15",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "퇴근",
  },
  {
    id: "EMP030",
    staffName: "서은채",
    dept: "고객서비스팀",
    position: "사원",
    phone: "010-0011-3344",
    email: "eunchae.seo@cinema.com",
    theater: "여의도점",
    hireDate: "2023-11-01",
    shiftType: "파트타임",
    role: "고객 응대",
    status: "휴가",
  },
  {
    id: "EMP031",
    staffName: "김태영",
    dept: "상영관팀",
    position: "사원",
    phone: "010-1122-5566",
    email: "taeyoung.kim@cinema.com",
    theater: "신촌점",
    hireDate: "2024-01-20",
    shiftType: "풀타임",
    role: "상영관 관리",
    status: "근무중",
  },
  {
    id: "EMP032",
    staffName: "이수현",
    dept: "매점팀",
    position: "사원",
    phone: "010-2233-6677",
    email: "suhyun.lee@cinema.com",
    theater: "명동점",
    hireDate: "2024-06-10",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "근무중",
  },
  {
    id: "EMP033",
    staffName: "박건우",
    dept: "운영팀",
    position: "매니저",
    phone: "010-3344-7788",
    email: "gunwoo.park@cinema.com",
    theater: "강남점",
    hireDate: "2021-03-01",
    shiftType: "풀타임",
    role: "지점 관리",
    status: "퇴사",
  },
  {
    id: "EMP034",
    staffName: "최예나",
    dept: "고객서비스팀",
    position: "대리",
    phone: "010-4455-8899",
    email: "yena.choi@cinema.com",
    theater: "홍대점",
    hireDate: "2022-10-15",
    shiftType: "풀타임",
    role: "매표",
    status: "근무중",
  },
  {
    id: "EMP035",
    staffName: "강민서",
    dept: "상영관팀",
    position: "사원",
    phone: "010-5566-9900",
    email: "minseo.kang@cinema.com",
    theater: "여의도점",
    hireDate: "2023-07-01",
    shiftType: "파트타임",
    role: "상영관 관리",
    status: "근무중",
  },
  {
    id: "EMP036",
    staffName: "정유나",
    dept: "매점팀",
    position: "사원",
    phone: "010-6677-0011",
    email: "yuna.jung@cinema.com",
    theater: "신촌점",
    hireDate: "2024-05-20",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "근무중",
  },
  {
    id: "EMP037",
    staffName: "오지훈",
    dept: "고객서비스팀",
    position: "사원",
    phone: "010-7788-1122",
    email: "jihun.oh@cinema.com",
    theater: "명동점",
    hireDate: "2023-09-01",
    shiftType: "풀타임",
    role: "고객 응대",
    status: "퇴근",
  },
  {
    id: "EMP038",
    staffName: "한예진",
    dept: "운영팀",
    position: "대리",
    phone: "010-8899-2233",
    email: "yejin.han@cinema.com",
    theater: "강남점",
    hireDate: "2022-06-10",
    shiftType: "풀타임",
    role: "운영 지원",
    status: "근무중",
  },
  {
    id: "EMP039",
    staffName: "윤하준",
    dept: "매점팀",
    position: "사원",
    phone: "010-9900-3344",
    email: "hajun.yoon@cinema.com",
    theater: "홍대점",
    hireDate: "2024-03-15",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "휴가",
  },
  {
    id: "EMP040",
    staffName: "서도현",
    dept: "상영관팀",
    position: "사원",
    phone: "010-0011-4455",
    email: "dohyun.seo@cinema.com",
    theater: "여의도점",
    hireDate: "2023-12-10",
    shiftType: "풀타임",
    role: "상영관 관리",
    status: "근무중",
  },
  {
    id: "EMP041",
    staffName: "김소희",
    dept: "고객서비스팀",
    position: "사원",
    phone: "010-1122-6677",
    email: "sohee.kim@cinema.com",
    theater: "신촌점",
    hireDate: "2024-02-01",
    shiftType: "파트타임",
    role: "고객 응대",
    status: "근무중",
  },
  {
    id: "EMP042",
    staffName: "이재민",
    dept: "매점팀",
    position: "사원",
    phone: "010-2233-7788",
    email: "jaemin.lee@cinema.com",
    theater: "명동점",
    hireDate: "2024-07-15",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "퇴근",
  },
  {
    id: "EMP043",
    staffName: "박시우",
    dept: "운영팀",
    position: "사원",
    phone: "010-3344-8899",
    email: "siwoo.park@cinema.com",
    theater: "강남점",
    hireDate: "2023-04-01",
    shiftType: "풀타임",
    role: "운영 지원",
    status: "근무중",
  },
  {
    id: "EMP044",
    staffName: "최윤서",
    dept: "고객서비스팀",
    position: "대리",
    phone: "010-4455-9900",
    email: "yunseo.choi@cinema.com",
    theater: "홍대점",
    hireDate: "2022-11-20",
    shiftType: "풀타임",
    role: "매표",
    status: "근무중",
  },
  {
    id: "EMP045",
    staffName: "강하영",
    dept: "상영관팀",
    position: "사원",
    phone: "010-5566-0011",
    email: "hayoung.kang@cinema.com",
    theater: "여의도점",
    hireDate: "2024-01-10",
    shiftType: "파트타임",
    role: "상영관 관리",
    status: "휴가",
  },
  {
    id: "EMP046",
    staffName: "정민재",
    dept: "매점팀",
    position: "사원",
    phone: "010-6677-1122",
    email: "minjae.jung@cinema.com",
    theater: "신촌점",
    hireDate: "2024-06-01",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "근무중",
  },
  {
    id: "EMP047",
    staffName: "오수진",
    dept: "고객서비스팀",
    position: "사원",
    phone: "010-7788-2233",
    email: "sujin.oh@cinema.com",
    theater: "명동점",
    hireDate: "2023-10-15",
    shiftType: "풀타임",
    role: "고객 응대",
    status: "퇴근",
  },
  {
    id: "EMP048",
    staffName: "한도윤",
    dept: "운영팀",
    position: "매니저",
    phone: "010-8899-3344",
    email: "doyoon.han@cinema.com",
    theater: "강남점",
    hireDate: "2021-05-01",
    shiftType: "풀타임",
    role: "지점 관리",
    status: "퇴사",
  },
  {
    id: "EMP049",
    staffName: "윤예린",
    dept: "매점팀",
    position: "사원",
    phone: "010-9900-4455",
    email: "yerin.yoon@cinema.com",
    theater: "홍대점",
    hireDate: "2024-04-20",
    shiftType: "파트타임",
    role: "매점 판매",
    status: "근무중",
  },
  {
    id: "EMP050",
    staffName: "서하준",
    dept: "상영관팀",
    position: "사원",
    phone: "010-0011-5566",
    email: "hajun.seo@cinema.com",
    theater: "여의도점",
    hireDate: "2023-08-01",
    shiftType: "풀타임",
    role: "상영관 관리",
    status: "근무중",
  },
];
=======
    { id: "EMP001", staffName: "김민수", dept: "운영팀", position: "매니저", phone: "010-1234-5678", email: "minsu.kim@cinema.com", theater: "강남점", hireDate: "2023-01-15", shiftType: "풀타임", role: "지점 관리", status: "근무중" },
    { id: "EMP002", staffName: "이서연", dept: "고객서비스팀", position: "대리", phone: "010-2345-6789", email: "seoyeon.lee@cinema.com", theater: "강남점", hireDate: "2023-06-01", shiftType: "풀타임", role: "매표", status: "근무중" },
    { id: "EMP003", staffName: "박지훈", dept: "운영팀", position: "사원", phone: "010-3456-7890", email: "jihoon.park@cinema.com", theater: "여의도점", hireDate: "2024-03-10", shiftType: "파트타임", role: "안내", status: "휴가" },
    { id: "EMP004", staffName: "최유진", dept: "매점팀", position: "사원", phone: "010-4567-8901", email: "yujin.choi@cinema.com", theater: "강남점", hireDate: "2024-07-20", shiftType: "파트타임", role: "매점 판매", status: "근무중" },
    { id: "EMP005", staffName: "강현우", dept: "상영관팀", position: "대리", phone: "010-5678-9012", email: "hyunwoo.kang@cinema.com", theater: "여의도점", hireDate: "2022-11-05", shiftType: "풀타임", role: "상영관 관리", status: "퇴근" },
    { id: "EMP006", staffName: "정소연", dept: "고객서비스팀", position: "사원", phone: "010-6789-0123", email: "soyeon.jung@cinema.com", theater: "신촌점", hireDate: "2023-09-12", shiftType: "파트타임", role: "고객 응대", status: "근무중" },
    { id: "EMP007", staffName: "오태현", dept: "운영팀", position: "매니저", phone: "010-7890-1234", email: "taehyun.oh@cinema.com", theater: "신촌점", hireDate: "2021-04-01", shiftType: "풀타임", role: "지점 관리", status: "퇴사" },
    { id: "EMP008", staffName: "한지민", dept: "매점팀", position: "사원", phone: "010-8901-2345", email: "jimin.han@cinema.com", theater: "강남점", hireDate: "2024-02-14", shiftType: "파트타임", role: "매점 판매", status: "근무중" },
    { id: "EMP009", staffName: "윤도현", dept: "상영관팀", position: "사원", phone: "010-9012-3456", email: "dohyun.yoon@cinema.com", theater: "여의도점", hireDate: "2023-12-01", shiftType: "풀타임", role: "상영관 관리", status: "휴가" },
    { id: "EMP010", staffName: "서민재", dept: "고객서비스팀", position: "대리", phone: "010-0123-4567", email: "minjae.seo@cinema.com", theater: "신촌점", hireDate: "2022-08-20", shiftType: "풀타임", role: "매표", status: "근무중" },
    { id: "EMP011", staffName: "김하늘", dept: "매점팀", position: "사원", phone: "010-1122-3344", email: "haneul.kim@cinema.com", theater: "홍대점", hireDate: "2024-05-10", shiftType: "파트타임", role: "매점 판매", status: "퇴근" },
    { id: "EMP012", staffName: "이준호", dept: "상영관팀", position: "사원", phone: "010-2233-4455", email: "junho.lee@cinema.com", theater: "명동점", hireDate: "2023-03-22", shiftType: "풀타임", role: "상영관 관리", status: "근무중" },
    { id: "EMP013", staffName: "박소영", dept: "고객서비스팀", position: "사원", phone: "010-3344-5566", email: "soyoung.park@cinema.com", theater: "홍대점", hireDate: "2024-01-15", shiftType: "파트타임", role: "고객 응대", status: "휴가" },
    { id: "EMP014", staffName: "최민혁", dept: "운영팀", position: "대리", phone: "010-4455-6677", email: "minhyuk.choi@cinema.com", theater: "강남점", hireDate: "2022-07-01", shiftType: "풀타임", role: "운영 지원", status: "근무중" },
    { id: "EMP015", staffName: "강지윤", dept: "매점팀", position: "사원", phone: "010-5566-7788", email: "jiyoon.kang@cinema.com", theater: "여의도점", hireDate: "2024-06-05", shiftType: "파트타임", role: "매점 판매", status: "근무중" },
    { id: "EMP016", staffName: "정우진", dept: "상영관팀", position: "사원", phone: "010-6677-8899", email: "woojin.jung@cinema.com", theater: "신촌점", hireDate: "2023-11-20", shiftType: "풀타임", role: "상영관 관리", status: "근무중" },
    { id: "EMP017", staffName: "오세진", dept: "고객서비스팀", position: "대리", phone: "010-7788-9900", email: "sejin.oh@cinema.com", theater: "명동점", hireDate: "2022-09-10", shiftType: "풀타임", role: "매표", status: "근무중" },
    { id: "EMP018", staffName: "한수민", dept: "매점팀", position: "사원", phone: "010-8899-0011", email: "sumin.han@cinema.com", theater: "강남점", hireDate: "2024-04-01", shiftType: "파트타임", role: "매점 판매", status: "휴가" },
    { id: "EMP019", staffName: "윤지성", dept: "운영팀", position: "매니저", phone: "010-9900-1122", email: "jisung.yoon@cinema.com", theater: "홍대점", hireDate: "2021-06-15", shiftType: "풀타임", role: "지점 관리", status: "퇴사" },
    { id: "EMP020", staffName: "서예린", dept: "고객서비스팀", position: "사원", phone: "010-0011-2233", email: "yerin.seo@cinema.com", theater: "여의도점", hireDate: "2023-10-05", shiftType: "파트타임", role: "고객 응대", status: "퇴근" },
    { id: "EMP021", staffName: "김지우", dept: "상영관팀", position: "사원", phone: "010-1122-4455", email: "jiwoo.kim@cinema.com", theater: "신촌점", hireDate: "2024-02-20", shiftType: "파트타임", role: "상영관 관리", status: "근무중" },
    { id: "EMP022", staffName: "이도윤", dept: "매점팀", position: "사원", phone: "010-2233-5566", email: "doyoon.lee@cinema.com", theater: "명동점", hireDate: "2024-08-01", shiftType: "파트타임", role: "매점 판매", status: "근무중" },
    { id: "EMP023", staffName: "박하린", dept: "고객서비스팀", position: "대리", phone: "010-3344-6677", email: "harin.park@cinema.com", theater: "강남점", hireDate: "2022-12-10", shiftType: "풀타임", role: "매표", status: "근무중" },
    { id: "EMP024", staffName: "최태민", dept: "운영팀", position: "사원", phone: "010-4455-7788", email: "taemin.choi@cinema.com", theater: "홍대점", hireDate: "2023-05-15", shiftType: "풀타임", role: "운영 지원", status: "퇴근" },
    { id: "EMP025", staffName: "강서준", dept: "상영관팀", position: "사원", phone: "010-5566-8899", email: "seojun.kang@cinema.com", theater: "여의도점", hireDate: "2024-03-01", shiftType: "파트타임", role: "상영관 관리", status: "휴가" },
    { id: "EMP026", staffName: "정민아", dept: "매점팀", position: "사원", phone: "010-6677-9900", email: "mina.jung@cinema.com", theater: "신촌점", hireDate: "2024-07-10", shiftType: "파트타임", role: "매점 판매", status: "근무중" },
    { id: "EMP027", staffName: "오현서", dept: "고객서비스팀", position: "사원", phone: "010-7788-0011", email: "hyunseo.oh@cinema.com", theater: "명동점", hireDate: "2023-08-20", shiftType: "풀타임", role: "고객 응대", status: "근무중" },
    { id: "EMP028", staffName: "한지호", dept: '운영팀', position: '대리', phone: '010-8899-1122', email: 'jiho.han@cinema.com', theater: '강남점', hireDate: '2022-05-01', shiftType: '풀타임', role: '운영 지원', status: '근무중' },
    { id: "EMP029", staffName: "윤서하", dept: "매점팀", position: "사원", phone: "010-9900-2233", email: "seoha.yoon@cinema.com", theater: "홍대점", hireDate: "2024-04-15", shiftType: "파트타임", role: "매점 판매", status: "퇴근" },
    { id: "EMP030", staffName: "서은채", dept: "고객서비스팀", position: "사원", phone: "010-0011-3344", email: "eunchae.seo@cinema.com", theater: "여의도점", hireDate: "2023-11-01", shiftType: "파트타임", role: "고객 응대", status: "휴가" },
    { id: "EMP031", staffName: "김태영", dept: "상영관팀", position: "사원", phone: "010-1122-5566", email: "taeyoung.kim@cinema.com", theater: "신촌점", hireDate: "2024-01-20", shiftType: "풀타임", role: "상영관 관리", status: "근무중" },
    { id: "EMP032", staffName: "이수현", dept: "매점팀", position: "사원", phone: "010-2233-6677", email: "suhyun.lee@cinema.com", theater: "명동점", hireDate: "2024-06-10", shiftType: "파트타임", role: "매점 판매", status: "근무중" },
    { id: "EMP033", staffName: "박건우", dept: "운영팀", position: "매니저", phone: "010-3344-7788", email: "gunwoo.park@cinema.com", theater: "강남점", hireDate: "2021-03-01", shiftType: "풀타임", role: "지점 관리", status: "퇴사" },
    { id: "EMP034", staffName: "최예나", dept: "고객서비스팀", position: "대리", phone: "010-4455-8899", email: "yena.choi@cinema.com", theater: "홍대점", hireDate: "2022-10-15", shiftType: "풀타임", role: "매표", status: "근무중" },
    { id: "EMP035", staffName: "강민서", dept: "상영관팀", position: "사원", phone: "010-5566-9900", email: "minseo.kang@cinema.com", theater: "여의도점", hireDate: "2023-07-01", shiftType: "파트타임", role: "상영관 관리", status: "근무중" },
    { id: "EMP036", staffName: "정유나", dept: "매점팀", position: "사원", phone: "010-6677-0011", email: "yuna.jung@cinema.com", theater: "신촌점", hireDate: "2024-05-20", shiftType: "파트타임", role: "매점 판매", status: "근무중" },
    { id: "EMP037", staffName: "오지훈", dept: "고객서비스팀", position: "사원", phone: "010-7788-1122", email: "jihun.oh@cinema.com", theater: "명동점", hireDate: "2023-09-01", shiftType: "풀타임", role: "고객 응대", status: "퇴근" },
    { id: "EMP038", staffName: "한예진", dept: "운영팀", position: "대리", phone: "010-8899-2233", email: "yejin.han@cinema.com", theater: "강남점", hireDate: "2022-06-10", shiftType: "풀타임", role: "운영 지원", status: "근무중" },
    { id: "EMP039", staffName: "윤하준", dept: "매점팀", position: "사원", phone: "010-9900-3344", email: "hajun.yoon@cinema.com", theater: "홍대점", hireDate: "2024-03-15", shiftType: "파트타임", role: "매점 판매", status: "휴가" },
    { id: "EMP040", staffName: "서도현", dept: "상영관팀", position: "사원", phone: "010-0011-4455", email: "dohyun.seo@cinema.com", theater: "여의도점", hireDate: "2023-12-10", shiftType: "풀타임", role: "상영관 관리", status: "근무중" },
    { id: "EMP041", staffName: "김소희", dept: "고객서비스팀", position: "사원", phone: "010-1122-6677", email: "sohee.kim@cinema.com", theater: "신촌점", hireDate: "2024-02-01", shiftType: "파트타임", role: "고객 응대", status: "근무중" },
    { id: "EMP042", staffName: "이재민", dept: "매점팀", position: "사원", phone: "010-2233-7788", email: "jaemin.lee@cinema.com", theater: "명동점", hireDate: "2024-07-15", shiftType: "파트타임", role: "매점 판매", status: "퇴근" },
    { id: "EMP043", staffName: "박시우", dept: "운영팀", position: "사원", phone: "010-3344-8899", email: "siwoo.park@cinema.com", theater: "강남점", hireDate: "2023-04-01", shiftType: "풀타임", role: "운영 지원", status: "근무중" },
    { id: "EMP044", staffName: "최윤서", dept: "고객서비스팀", position: "대리", phone: "010-4455-9900", email: "yunseo.choi@cinema.com", theater: "홍대점", hireDate: "2022-11-20", shiftType: "풀타임", role: "매표", status: "근무중" },
    { id: "EMP045", staffName: "강하영", dept: "상영관팀", position: "사원", phone: "010-5566-0011", email: "hayoung.kang@cinema.com", theater: "여의도점", hireDate: "2024-01-10", shiftType: "파트타임", role: "상영관 관리", status: "휴가" },
    { id: "EMP046", staffName: "정민재", dept: "매점팀", position: "사원", phone: "010-6677-1122", email: "minjae.jung@cinema.com", theater: "신촌점", hireDate: "2024-06-01", shiftType: "파트타임", role: "매점 판매", status: "근무중" },
    { id: "EMP047", staffName: "오수진", dept: "고객서비스팀", position: "사원", phone: "010-7788-2233", email: "sujin.oh@cinema.com", theater: "명동점", hireDate: "2023-10-15", shiftType: "풀타임", role: "고객 응대", status: "퇴근" },
    { id: "EMP048", staffName: "한도윤", dept: "운영팀", position: "매니저", phone: "010-8899-3344", email: "doyoon.han@cinema.com", theater: "강남점", hireDate: "2021-05-01", shiftType: "풀타임", role: "지점 관리", status: "퇴사" },
    { id: "EMP049", staffName: "윤예린", dept: "매점팀", position: "사원", phone: "010-9900-4455", email: "yerin.yoon@cinema.com", theater: "홍대점", hireDate: "2024-04-20", shiftType: "파트타임", role: "매점 판매", status: "근무중" },
    { id: "EMP050", staffName: "서하준", dept: "상영관팀", position: "사원", phone: "010-0011-5566", email: "hajun.seo@cinema.com", theater: "여의도점", hireDate: "2023-08-01", shiftType: "풀타임", role: "상영관 관리", status: "근무중" }
  ];          

 
>>>>>>> ee44428e6f70464f49fbb3cad2d41128779cd105
